# Generated by Django 4.2.1 on 2023-05-24 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("classes", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="englishclass",
            name="students",
        ),
        migrations.AddField(
            model_name="englishclass",
            name="students",
            field=models.ManyToManyField(
                related_name="students", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
