# Generated by Django 4.2.1 on 2023-05-23 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_user_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
