# Generated by Django 4.2.1 on 2023-06-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0003_remove_englishclass_students_englishclass_students"),
    ]

    operations = [
        migrations.AddField(
            model_name="englishclass",
            name="level",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B"), ("C", "C")], default="A", max_length=5
            ),
        ),
    ]
